/**
 * Copyright 2023 Code Biting S.L.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

module.exports = Object.freeze({
  RETURN_OK: 0,
  RETURN_NOT_SENT: -1,
  RETURN_NOT_FOUND: -4,
  RETURN_ERROR: -5,
  RETURN_EXCEPTION: -9,

  /*
  // Els substitueixen els ELECTROTEC_NODE_TYPE
  ELECTROTEC_LC1: 1,
  ELECTROTEC_DPA2: 2,
  ELECTROTEC_DPA1: 3,
  ELECTROTEC_DPAZ1: 4,
  ELECTROTEC_DPML24: 5,
  ELECTROTEC_LDIW1: 6,
  */

  ELECTROTEC_CHANNEL_1: '1',
  ELECTROTEC_CHANNEL_2: '2',

  ELECTROTEC_NO_BLINK: '0',
  ELECTROTEC_BLINK_0250: '1',
  ELECTROTEC_BLINK_0500: '2',
  ELECTROTEC_BLINK_1000: '4',

  ELECTROTEC_NO_SOUND: '0',
  ELECTROTEC_SOUND: '1',

  ELECTROTEC_NO_BEEP: '0',
  ELECTROTEC_ONE_BEEP: '1',
  ELECTROTEC_BEEP_SHORT_SHORT: '2',
  ELECTROTEC_BEEP_SHORT_LONG: '4',

  ELECTROTEC_COLOR_WHITE: '1,1,1',
  ELECTROTEC_COLOR_YELLOW: '1,1,0',
  ELECTROTEC_COLOR_MAGENTA: '1,0,1',
  ELECTROTEC_COLOR_RED: '1,0,0',
  ELECTROTEC_COLOR_CYAN: '0,1,1',
  ELECTROTEC_COLOR_GREEN: '0,1,0',
  ELECTROTEC_COLOR_BLUE: '0,0,1',
  ELECTROTEC_COLOR_BLACK: '0,0,0',

  ELECTROTEC_ARROWS_NONE: '0',
  ELECTROTEC_ARROWS_LEFTUP: '1',
  ELECTROTEC_ARROWS_RIGHTUP: '2',
  ELECTROTEC_ARROWS_LEFTDOWN: '3',
  ELECTROTEC_ARROWS_ROGHTDOWN: '4',
  ELECTROTEC_ARROWS_LEFT: '5',
  ELECTROTEC_ARROWS_ROGHT: '6',
  ELECTROTEC_ARROWS_UP: '7',
  ELECTROTEC_ARROWS_DOWN: '8',

  // type: string "display", "open", "version", "network", "relay"

  ELECTROTEC_MSGTYPE_DISPLAY: 'display',
  ELECTROTEC_MSGTYPE_DISPLAY_ACK: 'display_ack',
  ELECTROTEC_MSGTYPE_OPEN: 'open',
  ELECTROTEC_MSGTYPE_VERSION: 'version',
  ELECTROTEC_MSGTYPE_NETWORK: 'network',
  ELECTROTEC_MSGTYPE_RELAY: 'relay',
  ELECTROTEC_MSGTYPE_SESSIONS: 'sessions',
  ELECTROTEC_MSGTYPE_ALARM: 'alarm',
  ELECTROTEC_MSGTYPE_PRINT_RESPONSE: 'print',
  ELECTROTEC_MSGTYPE_KEY: 'key',
  ELECTROTEC_MSGTYPE_BROADCAST_DISPLAY: 'broadcast_display',

  ELECTROTEC_ALARM_RING_BROKEN: '1',
  ELECTROTEC_ALARM_NODE_DISCONNECT: '2',
  ELECTROTEC_ALARM_HW_ERROR: '3',
  ELECTROTEC_ALARM_WRONG_FORMAT: '4',
  ELECTROTEC_ALARM_NOT_CONFIG: '5',
  ELECTROTEC_ALARM_TRANSMISSION_FAIL: '6',

  ELECTROTEC_ACK_OK: '9',
  ELECTROTEC_ACK_NODE_DISCONNECTED: '2',
  ELECTROTEC_ACK_HW_ERROR: '3',
  ELECTROTEC_ACK_WRONG_FORMAT: '4',
  ELECTROTEC_ACK_NOT_CONFIG: '5',
  ELECTROTEC_ACK_TRANSMISSION_FAIL: '6',

  ELECTROTEC_NODE_TYPE_NOT_CONFIG: 0,
  ELECTROTEC_NODE_TYPE_DPA1: 1,
  ELECTROTEC_NODE_TYPE_DPAZ1: 2,
  ELECTROTEC_NODE_TYPE_DPM1: 3,
  ELECTROTEC_NODE_TYPE_DPMZ1: 4,
  ELECTROTEC_NODE_TYPE_LC1: 5,
  ELECTROTEC_NODE_TYPE_LCI2_LCIN1: 6,
  ELECTROTEC_NODE_TYPE_DPW1: 7,
  ELECTROTEC_NODE_TYPE_DPA2: 8,

  ELECTROTEC_NODE_STATE_UNK: '0',
  ELECTROTEC_NODE_STATE_INIT: '1',
  ELECTROTEC_NODE_STATE_LOCAL: '2',
  ELECTROTEC_NODE_STATE_NORMAL: '3',
  ELECTROTEC_NODE_STATE_ERROR: '4',
  ELECTROTEC_NODE_STATE_PROG: '5',

  SHELF_TYPE_PICK_TO_LIGHT: 1,
  SHELF_TYPE_PUT_TO_LIGHT: 2,
  SHELF_TYPE_PICK_TO_LIGHT_PT_PRODUCT: 3,
  SHELF_TYPE_PICK_TO_LIGHT_PT_ORDER: 4,
  SHELF_TYPE_PICK_TO_LIGHT_COMPETITION_GAME: 5,

  ORDER_PICK_TO_LIGHT: 1,
  ORDER_PUT_TO_LIGHT: 2,
  ORDER_PICK_TO_LIGHT_PT_PRODUCT: 3,
  ORDER_PICK_TO_LIGHT_PT_ORDER: 4,

  ORDER_PENDING: 1,
  ORDER_READY: 2,
  ORDER_RELEASING: 3,
  ORDER_EXECUTING: 4,
  ORDER_CANCELING: 5,
  ORDER_CANCELED: 6,

  MESSAGE_PENDING: 1,
  MESSAGE_PROCESSING: 2,
  MESSAGE_SEND: 3,
  MESSAGE_WAITING_RESPONSE: 4,
  MESSAGE_PROCESSING_RESPONSE: 5,
  MESSAGE_FINISHED: 6,

  // Constants per posar als camps origin i destiny de la taula missatges
  // Es contemplen missatges de onion a app, de app a ptl, de ptl a app i de app a onion
  MESSAGE_ACTOR_ONION: 'ONION',
  MESSAGE_ACTOR_PTL: 'PTL',
  MESSAGE_ACTOR_APP: 'APP',

  ACTION_GET: 'GET',
  ACTION_POST: 'POST',
  ACTION_PUT: 'PUT',
  ACTION_PATCH: 'PATCH',
  ACTION_DELETE: 'DELETE',
});
